project:
  type: website
  output-dir: docs

website:
  title: "Research Resources"
  page-navigation: true

  sidebar:
    style: "docked"
    search: true
    collapse-level: 2
    contents:
      - href: index.qmd
        text: Welcome

      - section: "R"
        contents:
          - href: r.qmd
            text: R Resources

format:
  html:
    page-layout: full
    css: styles.css
    theme: cosmo
    toc: true
    toc-location: right
    toc-depth: 3
    toc-title: "Table of contents"
    number-sections: false
    smooth-scroll: true
    code-fold: true
    code-tools: true
    mermaid:
      securityLevel: loose

editor: source

execute:
  freeze: auto
